spring.application.name=seletivo

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://db:5432/seletivo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do MinIO
minio.endpoint=http://minio:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=seletivo
minio.expiry=300

# Configurações de segurança JWT
jwt.secret=chaveSecretaParaGerarTokensJWTDeveSerBemLongaParaSeguranca
jwt.expiration=300000
jwt.refresh-expiration=600000

# Configurações CORS
cors.allowed-origins=http://localhost:8080
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Authorization,Content-Type
cors.exposed-headers=Authorization

# Configurações de paginação
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100


#spring.main.allow-bean-definition-overriding=true
